### ISSUE TITLE
Wrong permissions

### ISSUE THREAD

**Issue by metaxy** [elvanto/api-ruby#1]
When trying to include with `require 'elvanto` (which isnt documented) i get the following error:
```
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require': cannot load such file -- elvanto/client (LoadError)
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from /var/lib/gems/2.3.0/gems/elvanto-api-1.0.1/lib/elvanto.rb:6:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from create.rb:2:in `<main>'
```

The reason is:

```
ls -la /var/lib/gems/2.3.0/gems/elvanto-api-1.0.1/lib
drwxr-xr-x 3 root root 4096 Apr  7 11:48 .
drwxr-xr-x 3 root root 4096 Apr  7 11:48 ..
drwxr-xr-x 4 root root 4096 Apr  7 11:48 elvanto
-rw-rw-r-- 1 root root 3794 Apr  7 11:48 elvanto.rb
```
```
ls -la /var/lib/gems/2.3.0/gems/elvanto-api-1.0.1/lib/elvanto
drwxr-xr-x 4 root root 4096 Apr  7 11:48 .
drwxr-xr-x 3 root root 4096 Apr  7 11:48 ..
-rw------- 1 root root 2552 Apr  7 11:48 client.rb
-rw------- 1 root root 1557 Apr  7 11:48 error.rb
-rw------- 1 root root 5584 Apr  7 11:48 pager.rb
drwxr-xr-x 2 root root 4096 Apr  7 11:48 resources
-rw------- 1 root root   90 Apr  7 11:48 resources.rb
drwxr-xr-x 2 root root 4096 Apr  7 11:48 response
-rw------- 1 root root 2195 Apr  7 11:48 utils.rb
-rw-rw-r-- 1 root root   44 Apr  7 11:48 version.rb
```

The file client.rb is not readable.

**Comment by joshmcrae** [comment]
@metaxy This looks like it could be an issue with your specific Ruby/Gem installation or setup. I can see that the owner of those files is `root:root` which can happen if you install a Gem under `sudo`.

Are you using your system's Ruby installation or a tool like Rbenv on rvm? When you install Gems are you using `sudo`?
